// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elhlyxvzxuwnbrkrdsps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsaGx5eHZ6eHV3bmJya3Jkc3BzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODA0NTUsImV4cCI6MjA2MTU1NjQ1NX0.zvdNL0hNU3VPruSR9lZ1oCc1_wR1D0ikaDtWZBWOhd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);